
### set mp3 file on sonos device
POST https://relay-eu2.ezconnect.to/6e11c0a8c6e4fdd1686137c7c828e9afd5a0e0d3/www/music/sonos-music-client/sonos_soap_set_mp3.php

{"ip":"192.168.188.34","file":"/volume1/Music/Soundtracks/Hans Zimmer - Crimson Tide Main Theme.mp3"}

### play
POST https://relay-eu2.ezconnect.to/6e11c0a8c6e4fdd1686137c7c828e9afd5a0e0d3/www/music/sonos-music-client/sonos_soap_play.php

{"ip":"192.168.188.34"}

### volume
POST https://relay-eu2.ezconnect.to/6e11c0a8c6e4fdd1686137c7c828e9afd5a0e0d3/www/music/sonos-music-client/sonos_soap_volume.php

{"ip":"192.168.188.34", "volume":"1"}





### seek
POST https://relay-eu2.ezconnect.to/6e11c0a8c6e4fdd1686137c7c828e9afd5a0e0d3/www/music/sonos-music-client/sonos_soap_seek.php

{"ip":"192.168.188.34","duration":"30"}




### get
GET https://relay-eu2.ezconnect.to/6e11c0a8c6e4fdd1686137c7c828e9afd5a0e0d3/www/music/sonos-music-client/sonos_status.php?ip=192.168.188.34


